title: Seminar - DL for Sciences
description: Seminar - Deep Learning for Sciences
theme: just-the-docs

url: https://xxjsw.github.io/blogpost
search_enabled: false

# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
latex: katex